### ISSUE TITLE
Play Store lists apps as incompatible

### ISSUE THREAD

**Issue by masterdoctor** [masterdoctor/LineageOS-p8lite-community#1]
The Google Play store lists certain (but not all) apps as incompatible with the device. (Despite them being compatible [and available on the stock ROM]).

Known apps are:

- Instagram

- Snapchat

- XDA Forum

**Comment by ClassyLion** [comment]
XDA Forum is listed as incompatible.

**Comment by masterdoctor** [comment]
@ClassyLion Thanks

**Comment by ClassyLion** [comment]
There are lots of incompatible apps. Hard to find one that you can install, but most of the popular apps are incompatible.

**Comment by masterdoctor** [comment]
The apps work when installed through an APK file. @ClassyLion

**Comment by ClassyLion** [comment]
Best workaround for this bug is using Amazon App Store (Amazon Underground)

**Comment by masterdoctor** [comment]
Or Aptiode @ClassyLion

**Comment by LambdaSoft** [comment]
This can be a silly question but, someone has checked if the valor for "ro.product.name" line in the build.prop is the correct?

**Comment by masterdoctor** [comment]
Yes

**Comment by Untouch007** [comment]
I don't think people would have an issue with using Aptoide or finding an APK until the next stable release .

**Comment by Untouch007** [comment]
But I feel that we are getting this issue because the play Store is picking up l21, 02 and 23 to be android v6.0  and lower and some package files for nougat is different for the package file for marshmallows

**Comment by ClassyLion** [comment]
Yes, but it would be nice to have it working, so it needs to be worked on even though it is not an emergency.

**Comment by Untouch007** [comment]
May I ask what other version besides ale- l21 that has this issue? Or is it all 3?

**Comment by masterdoctor** [comment]
Fixed by @XePeleato
