### ISSUE TITLE
Headphone jack issues.

### ISSUE THREAD

**Issue by Zexorz** [masterdoctor/LineageOS-p8lite-community#11]
3pins Jack seems to be undetectable by phone.
However, 4pins (headphone + control buttons) one works fine.

**Comment by ClassyLion** [comment]
I used 3 pin headphones with it. Everything worked. It showed headphone icon on the NavBar and i could watch youtube videos and listen to them on headphones.
P.S. I have Numark HF 150 headphones.

**Comment by Zexorz** [comment]
Hmm, i use headphones with detachable cable on it. On stock they get detected, on Lineage it fails, so i thinked LineageOS has issue with it.

**Comment by masterdoctor** [comment]
@Zexorz Yes, that seems logical. I'll have a go with my headphones tonight.

**Comment by Untouch007** [comment]
tried 3 pairs of headphones ( all 3 pin ) maybe try a different set of headphones @Zexorz

**Comment by masterdoctor** [comment]
Reported as fixed in Experimental Update 1.0
