### ISSUE TITLE
ALE-L23 Wifi does not work

### ISSUE THREAD

**Issue by jona2428** [masterdoctor/LineageOS-p8lite-community#13]
Wifi does not work and shows MAC 02: 00: 00: 00: 00: 00

**Comment by west2554** [comment]
ALE-L02 Too
show
MAC 02: 00: 00: 00: 00: 00

**Comment by ClassyLion** [comment]
ALE-L21 showed that too after installation on the wifi connection installation step, but wifi works, it just says Mac adrese Unknown.

**Comment by masterdoctor** [comment]
I'm going to list this as a duplicate of the WiFi ALE-L02: https://github.com/masterdoctor/LineageOS-p8lite-community/issues/12
