### ISSUE TITLE
WIFI Mac adress won't show up

### ISSUE THREAD

**Issue by clarityzzz** [masterdoctor/LineageOS-p8lite-community#15]
Wifi adress won't show up under About Phone -> Status or under Wifi -> Settings thingy most likely due to the way wifi works on the ROM

**Comment by masterdoctor** [comment]
Yes (this is known and reported in the WiFi issue https://github.com/masterdoctor/LineageOS-p8lite-community/issues/12). WiFi is kind of dodgy. I'm going to look into the chipset later.
