### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by ClassyLion** [masterdoctor/LineageOS-p8lite-community#17]
Screen sometimes starts flickering. Sometimes partly or fully.
Screen flickers partly, when i use double tap to sleep. Then the NavBar and top edge of the screen under the NavBar flickers.
Sometimes, when i'm loading in to an app, when it changes screen it flickers. Looks like something to do with Material UI, because it flickers in parts of screen, not full screen the same. Each part flickers differently.

**Comment by masterdoctor** [comment]
I'm going to assume this is because there is no hardware compositing.
