### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by SinnloserTyp** [masterdoctor/LineageOS-p8lite-community#18]
Adding accounts not possible (In Settings, the menu crash)

**Comment by masterdoctor** [comment]
Can you get a `logcat`?

**Comment by SinnloserTyp** [comment]
Tomorrow i'll go back to the Custom ROM, then i can share one

**Comment by masterdoctor** [comment]
Okay, thanks @SinnloserTyp

**Comment by ClassyLion** [comment]
@masterdoctor How to get logcat without usb connection ar usb debugging?

**Comment by SinnloserTyp** [comment]
@ClassyLion it should only work with adb logcat? Without USB ,... you'll need Root, but Root is not avaible yet

**Comment by ClassyLion** [comment]
Btw, the bug persists even if i try to access an already added account, not only if you try to add a new one

**Comment by Untouch007** [comment]
I can log in accounts perfectly fine, but you have to install Gapps ARM64 ( i suggest the stock package ) this issue could be closed?

**Comment by ClassyLion** [comment]
I have tried all packages. You can log in to the first account, you cant add a second One through settings.
