### ISSUE TITLE
Google Assistant

### ISSUE THREAD

**Issue by Untouch007** [masterdoctor/LineageOS-p8lite-community#19]
I managed to get google assistant to start running on the rom but as soon as I restarted my Ale-L21 it couldn't open. Support issue?

**Comment by masterdoctor** [comment]
Google Assistant isn't supported on our phone...

**Comment by Untouch007** [comment]
i used one of the methods online and the app opened for a second.. Havent tested the app completely as it crashes all the time? support soon to be added??
Going to close for the time being...
