### ISSUE TITLE
Laggy Screen (LiveDisplay)

### ISSUE THREAD

**Issue by masterdoctor** [masterdoctor/LineageOS-p8lite-community#2]
The LiveDisplay feature (tints the screen orange in the evening to reduce eye strain) makes the Huawei P8-Lite very laggy.

**Comment by masterdoctor** [comment]
It seems to me that LiveDisplay isn't hardware-accelerated on our device.
It's recommended that you simply turn off LiveDisplay [or find a suitable alternative] until this is fixed.

**Comment by masterdoctor** [comment]
Can anybody on Experimental Release 1.0, test this?

**Comment by Untouch007** [comment]
Is the new release out ?

**Comment by ClassyLion** [comment]
It still decreases performance and Makss everything slower. I wouldnt call it lag, it just makes everything look like it has slower animations.

**Comment by Untouch007** [comment]
Is this issue going to be closed? Since it isn't hardware accelerated on our devices?

**Comment by masterdoctor** [comment]
I'm just discussing this with the other developers.
