### ISSUE TITLE
Sim2 does not work

### ISSUE THREAD

**Issue by west2554** [masterdoctor/LineageOS-p8lite-community#20]
insert Sim2 slot noservice.
edit : SD card work

**Comment by masterdoctor** [comment]
Can someone test this, please?

**Comment by Untouch007** [comment]
the slot does work but there is a catch... When I first tried both sim, sim 2 had no service.. i then removed sim 1 and left sim 2 in and restarted.. Sim 2 then worked. Then I put sim 1 back in and both worked perfectly... perhaps glitch with west2554? what model p8 lite are you using west?

**Comment by masterdoctor** [comment]
Interesting. @Untouch007 
Can some more people test this, I want to see whether this is always an issue.

**Comment by Bartixxx32** [comment]
Work now :D
