### ISSUE TITLE
Distorted voice conversations 

### ISSUE THREAD

**Issue by KernellyPoland** [masterdoctor/LineageOS-p8lite-community#21]
The voice is distorted or not clear sometimes only hear some words.

**Comment by Untouch007** [comment]
Are you sure it's not connection issues?

**Comment by KernellyPoland** [comment]
so the problem is resolved after returning to the software of Huawei So as I'm sure

**Comment by HakaiShimasu** [comment]
RIL malfunction!
Sometimes it works and sometimes not. 
The ROM is not ready ti ne used every day. 
Fix it and then is ready!!! 
Great job guys 👍, you are amazing!!
