### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by KernellyPoland** [masterdoctor/LineageOS-p8lite-community#22]
when erasing letters freezes or only when you click in the search bar disappear wczesnies erased letters. Working slowly.

**Comment by KernellyPoland** [comment]
when erasing letters freezes or only when you click in the search bar disappear before erases letters. Working slowly.*

**Comment by masterdoctor** [comment]
The stock browser is buggy. I believe you have to tap near the side to get the slide out menu.

**Comment by masterdoctor** [comment]
I'm going to replace the stock web browser with another one in my release - this is an AOSP browser problem not a ROM problem, so I'm going to close this.
