### ISSUE TITLE
root

### ISSUE THREAD

**Issue by amirve** [masterdoctor/LineageOS-p8lite-community#23]
how can i root my device again?

**Comment by Bartixxx32** [comment]
lineage or emui?

**Comment by Untouch007** [comment]
I'm pretty sure masterdoctor will release the next build with root binaries?

**Comment by amirve** [comment]
for linage
and i hope so

**Comment by Bartixxx32** [comment]
no why make build just use supersu https://download.chainfire.eu/696/supersu/

**Comment by masterdoctor** [comment]
With developer settings fixed, you will be able to root from there, otherwise a zip will be provided

**Comment by Bartixxx32** [comment]
i think no one guy tried dev options dont have root option

**Comment by ClassyLion** [comment]
In XePeleatos LineageOs dev options only come with root for ADB, no option for root to all apps. Its not full root.

**Comment by masterdoctor** [comment]
@ClassyLion Oh. In that case, I'll add some way of rooting - either through Settings or separate package.

**Comment by ClassyLion** [comment]
@masterdoctor In experimental release throught developer options there is only ADB option for root, i will try to flash SuperSU throught recovery now.

**Comment by ClassyLion** [comment]
Yes!!! Simply flashing through recovery SuperSU 2.79 zip from supersu homepage  made my device rooted. That was easy. :smile:
I could say that this is closed, because, maybe, not everyone wants root and that is as an optional thing.

**Comment by masterdoctor** [comment]
I agree. Thanks.

**Comment by ClassyLion** [comment]
Only thing is that it said something about boot.img doesnt support system-less root, or something.

**Comment by Untouch007** [comment]
when i tried flashing supersu 2.79.zip my device entered into a boot loop

**Comment by ClassyLion** [comment]
@Untouch007 While you flash root in recovery, it says, that there will be some reboots after flashing is finished, it is normal, just let them happen. How long did you wait?

**Comment by Untouch007** [comment]
@ClassyLion +- 15 min, the reason why i want to root is because my SD card is not being picked up by file explorers nor can any apps access it so i thought root might solve the problem... Also for some reason snapchat cannot connect to server with the rom but when i switch to stock it works. Any ideas?

**Comment by ClassyLion** [comment]
@Untouch007 SD card is a known bug. Root wont help and snapchat, it might be a problem with a custom rom.
