### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by ClassyLion** [masterdoctor/LineageOS-p8lite-community#25]
When trying a stress test on CPU, only the first core gets used. Second core uses max 15%. Like for some other task. Other cores are just offline.

**Comment by Untouch007** [comment]
looking into it

**Comment by masterdoctor** [comment]
@XePeleato Kernel issue?

**Comment by Untouch007** [comment]
Curious .... Does the Ale - l21 have a ARM 64 or standard ARM ? Because by the looks of it the system IMG is ARM64 based

**Comment by ClassyLion** [comment]
@Untouch007 Arm64

**Comment by XePeleato** [comment]
@masterdoctor It isn't a kernel issue. The kernel is able to start every core (from 0 to 7), taking a kmsg shows that there's no issues with that. If someone doesn't believe me or wants to see by themselves just run this command : `cat /sys/devices/system/cpu/online`.

The scheduler works and the cores can be activated, altough the rom may present some lag, that's true.

**Comment by ClassyLion** [comment]
Then why cpu doesnt use all cores even when stress test is in progress? Max 19%  cpu load.

**Comment by ClassyLion** [comment]
In Catlog, when i launch stress test, it shows "Suspending all threads took: xx ms" Why is it showing that? All the time.

**Comment by Bartixxx32** [comment]
maybe monitor mode (idk how its name in android) or somentig dont get corret informations this same is battery problem its not taking corrct Ampers

**Comment by Untouch007** [comment]
Updates on this issue?

**Comment by Bartixxx32** [comment]
xepeleato checking somentig now wait 🗡 🥇

**Comment by Untouch007** [comment]
@xepeleato stress test results after a few days of ROM use the second core I get no results. It's only the first core that gets used

**Comment by ClassyLion** [comment]
@Untouch007 The problem must be that workload isn't shared. All cores are supported by rom, but the workload isn't shared.

**Comment by Untouch007** [comment]
extremely laggy after 2 weeks of use... any updates ??

**Comment by Untouch007** [comment]
Can someone with an ALE -L21 download an app called syscheck from playstore and screenshot their info and upload it please. Think we can figure something out from there...
