### ISSUE TITLE
RIL

### ISSUE THREAD

**Issue by KernellyPoland** [masterdoctor/LineageOS-p8lite-community#26]
In the Polish mobile lose mobile network coverage
<br />
<br />Connectivity issues...

**Comment by xdk78** [comment]
Me too, but everyone has similar problem.

**Comment by Bartixxx32** [comment]
i dont tested now but i think is normal i set label as Bug

**Comment by XePeleato** [comment]
This happens because the Huawei Java RIL layer doesn't have the correct signal thresholds. It will be fixed.

**Comment by Untouch007** [comment]
Im guessing we will be waiting on this fix before the next update rolls out

**Comment by kaitek666** [comment]
Any chance of fixing this soon? I also noticed that it only wants to connect to LTE, never 3G/2G.

**Comment by masterdoctor** [comment]
Hi, @kaitek666 
The other developers are working on it - I have more exams to do before I can get back to it but it seems to me that this is almost fixed.

**Comment by Bartixxx32** [comment]
w jakich sieciach? / in what operators?

**Comment by kaitek666** [comment]
@Bartixxx32 I can confirm Play and Mobile Vikings.
