### ISSUE TITLE
32-bit ROM.

### ISSUE THREAD

**Issue by ClassyLion** [masterdoctor/LineageOS-p8lite-community#27]
Apparently, this rom is 32 bit.
![image](https://cloud.githubusercontent.com/assets/24903212/22260371/aea5a4c0-e271-11e6-865c-07444de10dd3.png)
Also, in CatLog, ABI is shown as "arm" no "arm64"

P.S. You can find lots of errors in CatLog.

**Comment by Untouch007** [comment]
There's the problem in #25 of cpu .... Can we just make 100% sure that all devices are ARM and not ARM64

**Comment by ClassyLion** [comment]
Our phone has 64-bit CPU

**Comment by Untouch007** [comment]
So the ROM is the issue... weird that it is trying to access lib64 and giving that error

**Comment by ClassyLion** [comment]
It's just running 32-bit OS on 64-bit CPU.

**Comment by XePeleato** [comment]
This discussion makes absolutely no sense. I'd recommend you to get informed about how processors work.

**Comment by ClassyLion** [comment]
@XePeleato I know a bit about CPUs, but i don't know anything much about mobile cpus. Thank you for explaining it all.

**Comment by Zexorz** [comment]
tbh you reopened @Bartixxx32

**Comment by Bartixxx32** [comment]
shiet xD

**Comment by masterdoctor** [comment]
Jesus, make up your mind 😂
