### ISSUE TITLE
RIL on Single SIM phone not working

### ISSUE THREAD

**Issue by masterdoctor** [masterdoctor/LineageOS-p8lite-community#28]
On my single SIM ALE-L21, the SIM card is not detected and in settings, I get options for a dual SIM phone.

**Comment by Bartixxx32** [comment]
try my rom and say me when working is somentig mybe your source iu have thsis same now fixed
http://104.199.98.71/ota2.zip

**Comment by Bartixxx32** [comment]
or mirror https://transfer.sh/mHj89/ota2.zip

**Comment by masterdoctor** [comment]
Possibly #26?
