### ISSUE TITLE
Wi-Fi speed not stable [ALE-L21 - Rooted and non-Rooted]

### ISSUE THREAD

**Issue by p8tgames** [masterdoctor/LineageOS-p8lite-community#30]
You can only launch 2 Apps max, to not drop below the 500kb/s zone (normally 2MB/s) YouTube will lag when set to 240p or higher.

**Comment by p8tgames** [comment]
On L23 too.

**Comment by p8tgames** [comment]
https://drive.google.com/file/d/0BxwhXdzjlWWcaUZYUElvQjBELU0/view?usp=drivesdk Here's a logcat of me watching a Video on 720p res.

**Comment by masterdoctor** [comment]
@p8tgames Are you sure the YouTube lag isn't a graphics issue?
Also, can you use this speed test: http://speedtest.googlefiber.net/ and test on EMUI and LineageOS

**Comment by p8tgames** [comment]
Yeah here we go! EMUI: 20.3 MB/s DL 4MB/s UL
Lineage: 10.4 MB/s DL 2.8 MB/s UL. In YouTube i am not quite sure. I am now going to try an YouTube mod.
