### ISSUE TITLE
when the work is completed?

### ISSUE THREAD

**Issue by KernellyPoland** [masterdoctor/LineageOS-p8lite-community#31]
when you can expect a fully functioning software?

**Comment by Bartixxx32** [comment]
never good night

**Comment by Bartixxx32** [comment]
really we dont have eta

**Comment by Bartixxx32** [comment]
2 years are enught

**Comment by Untouch007** [comment]
Be patient dude

**Comment by Zexorz** [comment]
"wontfix" tag killed me xD

**Comment by Vikanen** [comment]
But it's pretty much true as we have HiSilicon

**Comment by masterdoctor** [comment]
Speculation and unconstructive
