### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by Untouch007** [masterdoctor/LineageOS-p8lite-community#33]
snapchat keeps on persisting that it cannot connect to server

**Comment by masterdoctor** [comment]
Do you have Xposed installed?

**Comment by Untouch007** [comment]
on stock rom i had it installed yes... but with lineage i cant seem to get the root binaries installed and the xpoesed for p8 lite was for marshmallow only... Do you perhaps have links to rooting and xposed installer for lineage p8 lite?

**Comment by ClassyLion** [comment]
Xposed for nougat is not released yet.

**Comment by masterdoctor** [comment]
Oh. My bad @ClassyLion

**Comment by masterdoctor** [comment]
This is an issue with LineageOS.
It doesn't pass the Snapchat safetynet check.
https://www.reddit.com/r/LineageOS/comments/5q0uqj/lineage_os_passes_safetynet_checks/dcx9yyv/
