### ISSUE TITLE
Ear Speaker doesn't work

### ISSUE THREAD

**Issue by masterdoctor** [masterdoctor/LineageOS-p8lite-community#7]
Ear Speaker doesn't work in calls, etc.

**Comment by HakaiShimasu** [comment]
@masterdoctor When you turn-off speakerphone in call, it activate the "do not disturb" mode..

**Comment by masterdoctor** [comment]
I wonder if the system isn't detecting/initialising the earspeaker then @HakaiShimasu

**Comment by HakaiShimasu** [comment]
@masterdoctor The device will not crash, so I think the system initialize the earspeaker but it don't pass the audio...

**Comment by masterdoctor** [comment]
Fixed.

**Comment by HakaiShimasu** [comment]
Amazing!

**Comment by masterdoctor** [comment]
Some people are reporting that there is distorted (call) audio from the Ear Speaker but apparently this is also a problem with regular speaker too. So I'm going to call that a separate issue, see this: https://github.com/masterdoctor/LineageOS-p8lite-community/issues/21

**Comment by HakaiShimasu** [comment]
@masterdoctor When do you update the system image with this fix? 
I had to uninstall the ROM for this problem. But if you have fixed it I re-install it!

**Comment by masterdoctor** [comment]
I'm releasing updates tonight - and with ZIPs too.

**Comment by Untouch007** [comment]
That's great news lets us know when its up
