### ISSUE TITLE
Filters on Main Camera don't work

### ISSUE THREAD

**Issue by masterdoctor** [masterdoctor/LineageOS-p8lite-community#8]
"[...] filters work on selfie cam, but when i use filter on main camera, they like turn on and imediately turn off."
[Quoted from HuanityBRB on the P8-Lite LineageOS thread.](https://forum.xda-developers.com/showpost.php?p=70633477&postcount=646)

**Comment by ClassyLion** [comment]
Apparently, this issue fixed itself after wiping everything except System. And (dont know if it matters) installing gapps

**Comment by masterdoctor** [comment]
It could just be a problem with data or cache.
I'll mark as closed.
