### ISSUE TITLE
Cant access SD card

### ISSUE THREAD

**Issue by ClassyLion** [masterdoctor/LineageOS-p8lite-community#9]
No app can access SD card. 
Music doesnt show up in music app.
File manager cant see it, even if I go to root storage in it.

It can only be accessed by clicking on the notification about the SD card (For transferring photos and media).
Phone sees it as portable storage.

**Comment by masterdoctor** [comment]
Thanks, I'll take a look into it.
I think it might be an fstab issue.

**Comment by HakaiShimasu** [comment]
If you open download app, you can access to SD Card
Ps. Sorry for my English. #

**Comment by masterdoctor** [comment]
Interesting, @HakaiShimasu - So it must be a userspace bug.
I'll have a look and see if I can work out what may be causing it.

**Comment by ClassyLion** [comment]
@HakaiShimasu When you access SD card through downloads app, its the same as pressing on the notification about SD card in NavBar. Phone can see the SD card, but apps dont see it.

**Comment by HakaiShimasu** [comment]
@ClassyLion No no, you can access to SD card without press the notification in nav bar. If you open directly download app and open the navigation menu, you can access to SD card. It is only app can see the SD card.. I don't understand because other app don't see it.

**Comment by HakaiShimasu** [comment]
@ClassyLion the problem of Linux is for quick start of windows.. If you disable it Linux see the disk part.

**Comment by ClassyLion** [comment]
@HakaiShimasu When you open it through download app its the same as through NavBar, you can see that. Open through download app and then press on the notification to open it. Its the same.
And my linux can see that partition, simply no matter what i do, some apps dont have permission to write there, apparently. They can read, but they cant write.

**Comment by HakaiShimasu** [comment]
@ClassyLion Ah ok ok. I thought of another thing. You are right.

**Comment by masterdoctor** [comment]
Okay. So it's a permission issue?
(I'll test this tonight with a debug app)

**Comment by HakaiShimasu** [comment]
@masterdoctor Probably yes, but I'm not sure at 100%.
